In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)


numpy.ndarray

In [6]:
a.shape


(3,)

In [8]:
a = a.reshape(1,-1)

In [9]:
a.shape


(1, 3)

In [10]:
a = np.array([1,2,3,4,5,6])


In [11]:
a.shape 


(6,)

In [12]:
a = a.reshape(2,-1)

In [13]:
a.shape

(2, 3)

In [14]:
a = a.reshape(-1,2)

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a[2,0]

5

### zeros

In [18]:
a = np.zeros((3,3))

In [19]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a = np.ones((3,3))

In [21]:
a


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### full

In [22]:
a = np.full((3,3),0)

In [23]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
a = np.full((1,3),1)

In [25]:
a

array([[1, 1, 1]])

### eye

In [26]:
a = np.eye(3)

In [27]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random.random

In [28]:
a = np.random.random((3,4))

In [29]:
a

array([[0.89474328, 0.48827205, 0.27964451, 0.03423617],
       [0.89439787, 0.67375857, 0.86794077, 0.62479318],
       [0.20084925, 0.4087474 , 0.29691081, 0.78936979]])

In [30]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [31]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
a[1,-2]

7

In [34]:
a[np.arange(3),1] += 10

In [35]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [36]:
np.arange(3)

array([0, 1, 2])

In [37]:
np.arange(3,7)

array([3, 4, 5, 6])

In [38]:
a[np.arange(3),[1,1,1]] += 10

In [39]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [41]:
a[[0,1,2],[1,1,1]] += 10

In [42]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [43]:
result_index = a > 10

In [44]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [46]:
b = a[result_index]

In [47]:
b

array([32, 36, 40, 11, 12])

In [48]:
a[a>10]

array([32, 36, 40, 11, 12])

## 元素的数据类型

In [49]:
a = np.array([1,2])

In [50]:
a.dtype

dtype('int32')

In [51]:
a = np.array([2,1.2])

In [52]:
a.dtype

dtype('float64')

In [54]:
a = np.array([1.2,1.4],dtype=np.int64)

In [55]:
a

array([1, 1], dtype=int64)

## 数学运算与常用函数

In [57]:
a = np.array([[1,2],[3,4]])

In [58]:
b= np.array([[1,2],[3,4]])

In [59]:
a + b

array([[2, 4],
       [6, 8]])

In [60]:
np.add(a,b)

array([[2, 4],
       [6, 8]])

In [61]:
a - b

array([[0, 0],
       [0, 0]])

In [62]:
np.subtract(a,b)

array([[0, 0],
       [0, 0]])

In [63]:
a * b

array([[ 1,  4],
       [ 9, 16]])

In [64]:
np.multiply(a,b)

array([[ 1,  4],
       [ 9, 16]])

In [65]:
a / b

array([[1., 1.],
       [1., 1.]])

In [66]:
np.divide(a,b)

array([[1., 1.],
       [1., 1.]])

In [67]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
b = np.array([[1,2,3],[4,5,6]])

In [70]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [71]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [72]:
np.sum(a)

10

In [73]:
a.sum()

10

In [74]:
a.sum(axis=0)

array([4, 6])

In [75]:
a.sum(axis=1)

array([3, 7])

In [76]:
np.mean(a)

2.5

In [77]:
np.mean(a,axis=0)

array([2., 3.])

In [78]:
np.random.uniform(3,4)

3.843224268577598

In [80]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [81]:
np.tile(a,(2,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [82]:
a.argsort()

array([[0, 1],
       [0, 1]], dtype=int64)

In [83]:
a

array([[1, 2],
       [3, 4]])

In [84]:
a.argsort(axis=0)

array([[0, 0],
       [1, 1]], dtype=int64)

In [85]:
a.argsort(axis=1)

array([[0, 1],
       [0, 1]], dtype=int64)

# 以上结果是数组下标

In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
a.T

array([[1, 3],
       [2, 4]])

In [88]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [89]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])

In [90]:
b=np.array([1,2,3])

In [91]:
for i in range(4):
    a[i,:] += b

In [92]:
a

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

# 广播

In [93]:
a 

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [94]:
a + np.tile(b,(4,1))

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [ 9, 12, 15],
       [12, 15, 18]])

In [95]:
a + b

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [ 9, 12, 15],
       [12, 15, 18]])